{
  "BeforeCallCommon": null,
  "AfterCallCommon": null,
  "RecordHeaders": false,
  "RecordParameters": false,
  "Name": "subTest2.rest",
  "BaseName": "subTest2",
  "Requests": [
    {
      "ProxyHost": null,
      "ProxyPort": null,
      "ProxyUser": null,
      "ProxyPwd": null,
      "Name": "Get_All_Objects",
      "Url": "http://localhost:3000/students",
      "Method": "GET",
      "Body": "",
      "Credential": null,
      "BeforeCallCommon": null,
      "AfterCallCommon": null,
      "BeforeCall": null,
      "AfterCall": null,
      "Headers": [],
      "Parameters": []
    },
    {
      "ProxyHost": null,
      "ProxyPort": null,
      "ProxyUser": null,
      "ProxyPwd": null,
      "Name": "Post_Data",
      "Url": "http://localhost:3000/students",
      "Method": "POST",
      "Body": "\r\n  {\r\n    \"id\": \"7\",\r\n    \"name\": \"S Chandrakanth\",\r\n    \"location\": \"TVM\",\r\n    \"phone\": 887676755543\r\n  }\r\n",
      "Credential": null,
      "BeforeCallCommon": null,
      "AfterCallCommon": null,
      "BeforeCall": null,
      "AfterCall": null,
      "Headers": [],
      "Parameters": []
    },
    {
      "ProxyHost": null,
      "ProxyPort": null,
      "ProxyUser": null,
      "ProxyPwd": null,
      "Name": "Delete_By_Id",
      "Url": "http://localhost:3000/students/4",
      "Method": "DELETE",
      "Body": "",
      "Credential": null,
      "BeforeCallCommon": null,
      "AfterCallCommon": null,
      "BeforeCall": null,
      "AfterCall": null,
      "Headers": [],
      "Parameters": []
    },
    {
      "ProxyHost": null,
      "ProxyPort": null,
      "ProxyUser": null,
      "ProxyPwd": null,
      "Name": "Patch_User_Data",
      "Url": "",
      "Method": "GET",
      "Body": "",
      "Credential": null,
      "BeforeCallCommon": null,
      "AfterCallCommon": null,
      "BeforeCall": null,
      "AfterCall": null,
      "Headers": [],
      "Parameters": []
    }
  ]
}