{
  "BeforeCallCommon": null,
  "AfterCallCommon": null,
  "RecordHeaders": false,
  "RecordParameters": false,
  "Name": "subTest2.rest",
  "BaseName": "subTest2",
  "Requests": [
    {
      "ProxyHost": null,
      "ProxyPort": null,
      "ProxyUser": null,
      "ProxyPwd": null,
      "Name": "Get_All_Students",
      "Url": "http://localhost:3000/students",
      "Method": "GET",
      "Body": "",
      "Credential": null,
      "BeforeCallCommon": null,
      "AfterCallCommon": null,
      "BeforeCall": null,
      "AfterCall": null,
      "Headers": [],
      "Parameters": []
    },
    {
      "ProxyHost": null,
      "ProxyPort": null,
      "ProxyUser": null,
      "ProxyPwd": null,
      "Name": "Post_Student",
      "Url": "http://localhost:3000/students",
      "Method": "POST",
      "Body": "\r\n  {\r\n    \"id\": \"{id}\",\r\n    \"name\": \"{name}\",\r\n    \"location\": \"{location}\",\r\n    \"phone\": \"{phone}\"\r\n  }\r\n",
      "Credential": null,
      "BeforeCallCommon": null,
      "AfterCallCommon": null,
      "BeforeCall": null,
      "AfterCall": null,
      "Headers": [],
      "Parameters": [
        {
          "Name": "id",
          "TokenName": "{id}",
          "Value": "1"
        },
        {
          "Name": "name",
          "TokenName": "{name}",
          "Value": "Shahana S"
        },
        {
          "Name": "location",
          "TokenName": "{location}",
          "Value": "TVM"
        },
        {
          "Name": "phone",
          "TokenName": "{phone}",
          "Value": "638958924894"
        }
      ]
    },
    {
      "ProxyHost": null,
      "ProxyPort": null,
      "ProxyUser": null,
      "ProxyPwd": null,
      "Name": "Delete_By_Id",
      "Url": "http://localhost:3000/students/1",
      "Method": "DELETE",
      "Body": "",
      "Credential": null,
      "BeforeCallCommon": null,
      "AfterCallCommon": null,
      "BeforeCall": null,
      "AfterCall": null,
      "Headers": [],
      "Parameters": []
    },
    {
      "ProxyHost": null,
      "ProxyPort": null,
      "ProxyUser": null,
      "ProxyPwd": null,
      "Name": "Patch_Student_By_Id",
      "Url": "http://localhost:3000/students/5",
      "Method": "PATCH",
      "Body": "{\r\n  \"name\": \"{name}\",\r\n  \"location\": \"{location}\",\r\n  \"phone\": \"{phone}\"\r\n}",
      "Credential": null,
      "BeforeCallCommon": null,
      "AfterCallCommon": null,
      "BeforeCall": null,
      "AfterCall": null,
      "Headers": [],
      "Parameters": [
        {
          "Name": "id",
          "TokenName": "{id}",
          "Value": "5"
        },
        {
          "Name": "name",
          "TokenName": "{name}",
          "Value": "Sambit"
        },
        {
          "Name": "location",
          "TokenName": "{location}",
          "Value": "Tvm"
        },
        {
          "Name": "phone",
          "TokenName": "{phone}",
          "Value": "56734567"
        }
      ]
    },
    {
      "ProxyHost": null,
      "ProxyPort": null,
      "ProxyUser": null,
      "ProxyPwd": null,
      "Name": "Get_Student_By_Id",
      "Url": "http://localhost:3000/students/{id}",
      "Method": "GET",
      "Body": "",
      "Credential": null,
      "BeforeCallCommon": null,
      "AfterCallCommon": null,
      "BeforeCall": null,
      "AfterCall": null,
      "Headers": [],
      "Parameters": [
        {
          "Name": "id",
          "TokenName": "{id}",
          "Value": "9"
        }
      ]
    },
    {
      "ProxyHost": null,
      "ProxyPort": null,
      "ProxyUser": null,
      "ProxyPwd": null,
      "Name": "Get_Student_By_Id_404",
      "Url": "http://localhost:3000/students/{id}",
      "Method": "GET",
      "Body": "",
      "Credential": null,
      "BeforeCallCommon": null,
      "AfterCallCommon": null,
      "BeforeCall": null,
      "AfterCall": null,
      "Headers": [],
      "Parameters": [
        {
          "Name": "id",
          "TokenName": "{id}",
          "Value": "79"
        }
      ]
    }
  ]
}